theme: jekyll-theme-minimal
title: [Call me Millicent !!]
logo: https://github.com/mylyfabre/eportfolio/issues/1
description: [Engineering Student & Violonist]
description: [Orgin: Petit-Goave, Haiti]
