baseURL ="https://mylyfabre.github.io/eportfolio/"
languageCode="en-us" 
title = "notrack"
newContentEditor= "nvim" 
mainSections= ["blog"] 
#disqusShortname = "example" 
paginate = 4 

[params] 
author ="Hugo de Groot" 
siteHeading = "Hugo Grotius" # defaults to author 
showSections = ["blog"] 
showtaxonomyLinks= false 
nBlogLatest = 4 # number of blog post on the home page 
blog LatextHeading = " My Writing" 


[params.social] 
github ="example" 
linkedin ="example" 
email = "example@example.com" 
mastodon= "example" 
keybase ="example" 

[taxonomies] 
year = "year" 
month ="month" 
tags ="tags" 
categories ="categories" 

[permalinks] 
blog ="[/blog/:year/:month/:slug"

